name: testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Print bash version
        run: |
          bash --version
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y bsdmainutils
      - name: Test with bash script
        run: |
          bash example.sh -a 99 --gender male

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Print bash version
        run: |
          bash --version
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew update && brew install bash util-linux
      - name: Test with bash script
        run: |
          bash example.sh -a 99 --gender male
  # test-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Print bash version
  #       shell: bash
  #       run: |
  #         bash --version
  #     - uses: actions/checkout@v2
  #     - name: Test with bash script
  #       shell: bash
  #       run: |
  #         bash example.sh -a 99 --gender male
